### ISSUE TITLE
Mailadresse barcheck@vivaconagua anlegen

### ISSUE THREAD

**Issue by AnnikaB0408** [Viva-con-Agua/barcheck#112]

**Comment by ansgarmax** [comment]
- Mail barcheck ist created and FWDs to Ansgar, @LaimaL and @AnnikaB0408 
- Auto Respond looks like this: 

Vielen Dank für Deine Nachricht!

Diese Mailadresse wird von Ansgar (VcA), Laima (SAP) und Annika (SAP) als Teile des Barcheck-Projektteams gelesen.

Im Zuge der Testphase wird Annika sich um Dein Anliegen kümmern.

Viele Grüsse,

Das Barcheck-Team

**Comment by ansgarmax** [comment]
@Mail should end with .com
