### ISSUE TITLE
JSON Template aus Berlin

### ISSUE THREAD

**Issue by noravth** [Viva-con-Agua/barcheck#17]
net::ERR_TUNNEL_CONNECTION_FAILED

wenn:
	console.log("worked1");
	var formData = {
		"metaData": {
			"microServiceName": "",
			"template": "",
			"searchEngineKeywords": "simpleTemplate",
			"language": "",
			"organization": ""
		},
		"templateData": {
			"title": "",
			"header": "<head></head>",
			"body": "<body></body>"
		}
	};

	$.ajax({
		url: "https://vca.informatik.hu-berlin.de:80/api/dispenser/getTemplate",
		method: 'GET',
		data: formData
	}).success(function(data) {
		console.log(data);
	}).error(function(data){
		console.log("");
	});

**Comment by benediktbosshammer** [comment]
Ich habe eine Mail von Dennis, die erklärt wie wir es lösen können
